name: Deploy to GOV.UK PaaS

on:
  push:
    branches: [ add-deploys ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install CloudFoundry CLI
        shell: bash
        id: install-cf-cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli

      - name: Deploy to Gov.uk PaaS
        id: deploy-to-paas
        shell: bash
        run: |
          cf api ${{ secrets.CF_API }}
          cf auth "${{ secrets.CF_USER }}" "${{ secrets.CF_PASSWORD }}"
          cf target -o ${{ secrets.CF_ORGANISATION }} -s ${{ secrets.CF_SPACE }}
          cf push -f ./manifest.yml
